name: Deploy ZKP-Labs Blog

on:
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    name: deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install mbbook cli
        run: cargo install mdbook

      - name: Build mdbook
        run: mdbook build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Delete current blog
        run: |
          sleep 5
          aws s3 rm s3://${{ secrets.AWS_S3_STORAGE }}/ --recursive

      - name: Deploy latest blog
        run: |
          sleep 10
          aws s3 cp ./book s3://${{ secrets.AWS_S3_STORAGE }}/ --recursive
